common: &common
  tag_groups:
    - [login, register, logged-in, facebook]
    - [facebook_login, facebook_register]

test:
  <<: *common

development:
  <<: *common

production:
  <<: *common
  auth:
    name: bla
    password: blub

  deploy:
    servers:
      - foo
      - bar

staging:
  <<: *common
  deploy:
    servers:
      - foo
      - bar
